@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!include ICONURL/material/border_all.puml
!include ICONURL/material/folder.puml
!include ICONURL/material/description.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/postgresql.puml
!include DEVICONS/google_drive.puml
!include DEVICONS/database.puml
!include DEVICONS/javascript.puml

HIDE_STEREOTYPE()
SET_SKETCH_STYLE($bgColor="white", $footerWarning="Draft", $footerText="Created for discussion")
LAYOUT_AS_SKETCH()
LAYOUT_LEFT_RIGHT()
UpdateElementStyle("", $shadowing="true")

title: "Thematic Data Component Diagram"

AddElementTag("tool", $shape=EightSidedShape(), $legendText="tool (eight sided)")
AddRelTag("old", $textColor=$ARROW_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())

Person(ip, "Implementing Partner")
Person(acor, "A/COR")

ContainerDb(postgres, "Mission Database", "PostgreSQL", "Single source of truth for the Mission", $sprite="postgresql")

System_Boundary(dataHub, "Data Hub"){
    Component(dataCatalog, "Data Catalog", "Google Apps Script", "Share thematic data")
    Component(mapViewer, "Map Viewer", "Google Apps Script", "Map thematic data")
}

System_Boundary(activityFolder, "Activity Folder"){
    Component(dataInventory, "Data Inventory", "Google Sheets", "List of all datasets to be collected", $sprite="border_all")
    Component(activityMELP, "Activity MECLA Plan & DMP", "Google Doc", "Activity MECLA and Data Management Plan", $sprite="description")
    Component(thematicData, "Thematic Datasets", "Google Folder", "Submit thematic datasets and data documentation", $sprite="folder")
    Component(deliverables, "Intellectual Works", "Google Folder", "Submit reports and other intellectual works", $sprite="folder")
}

Boundary(agency, "Agency Systems"){
    Container_Ext(ddl, DDL)
    Container_Ext(dec, DEC)
}

System_Boundary(meclaLib, "MECLA Library"){
    Component(thematicDb, "Thematic Database", "Google Folder", $sprite="folder")
}

Container(myUSAID, "PPSO", "MyUSAID", "Internal knowledge management site")

Rel_Neighbor(ip, activityFolder, "updates")
Rel_U(activityFolder, acor, "reviews")
Rel_L(activityMELP, dataInventory, " ")
Rel(dataInventory, thematicData, " ")
Rel(dataInventory, deliverables, " ")
Rel(thematicData, postgres, "uploads", "Data Steward", $tags="old")
Rel(ddl, postgres, "uploads", "Data Steward")
Rel(deliverables, dec, "submits","Implementing Partner")
Rel(thematicData, ddl, "submits", "Implementing Partner")
Rel_Neighbor(postgres, thematicDb, "upload", "Data Steward")
Rel(thematicDb, dataCatalog, " ")
Rel(thematicDb, mapViewer, " ")
Rel_L(dec, myUSAID, " ")
