@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!include DEVICONS/postgresql.puml
!include DEVICONS/google_drive.puml
!include DEVICONS2/javascript.puml

HIDE_STEREOTYPE()
LAYOUT_LEFT_RIGHT()
SET_SKETCH_STYLE($bgColor="white", $footerWarning="Draft", $footerText="Created for discussion")
LAYOUT_AS_SKETCH()
UpdateElementStyle("", $shadowing="true")

title: "Mission Data Management System Overview"

System(apps, "Web Apps", "Make data discoverable", $sprite=javascript)
System(cloud, "Google Drive", "Leverage the Google Workspace tools you know", $sprite="google_drive")
System(missionDb, "Mission Database", "Bring all your data together", $sprite="postgresql")

Rel_U(cloud, apps, "reads")
Rel_D(cloud, missionDb, "aggregates")

' Person(acor, "A/COR")
' Person(ip, "Implementing Partner")
' Person(ds, "Data Steward")

' System(dms, "Mission Data Management System", "Single-source of truth for the Mission")

' Boundary(agency, "Agency Systems"){
'     System_Ext(dis, "DIS", "Development Information System")
'     System_Ext(ddl, "DDL", "Development Data Library")
'     System_Ext(dec, "DEC", "Development Experience Clearinghouse")
' }

' Lay_R(dis, ddl)
' Lay_R(ddl, dec)

' Rel(acor, dms, "updates")
' Rel_R(ip, ddl, "submits to")
' Rel_R(ip, dms, "submits to")
' BiRel_D(dms, ddl, "integrates", "Data Steward")
' Rel(ds, dms, "queries/maintains")
' Rel_L(ds, acor, "shares data & analysis")
' Rel(acor, ip, "coordinates with")

@enduml